# docker run -p 8761:8761 fernandodelima/naming-server:0.0.1-SNAPSHOT

services:
  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
      - fernando-network

  naming-server:
    image: fernandodelima/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
    depends_on:
      - zipkin-server
    networks:
      - fernando-network

  api-gateway:
    image: fernandodelima/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    restart: always
    depends_on:
      - zipkin-server
      - naming-server
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - fernando-network

  book-db:
    image: mysql:9.3.0
    ports:
      - 3310:3306
    restart: always
    environment:
      TZ: America/Pernambuco
      MYSQL_ROOT_PASSWORD: fernando
      MYSQL_USER: docker 
      MYSQL_PASSWORD: fernando 
      MYSQL_DATABASE: book_service
    networks:
      - fernando-network

  exchange-db:
    image: mysql:9.3.0
    ports:
      - 3308:3306
    restart: always
    environment:
      TZ: America/Pernambuco
      MYSQL_ROOT_PASSWORD: fernando
      MYSQL_USER: docker
      MYSQL_PASSWORD: fernando
      MYSQL_DATABASE: exchange_service
    networks:
      - fernando-network

  exchange-service:
    image: fernandodelima/exchange-service:0.0.1-SNAPSHOT
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://exchange-db:3306/exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: fernando
    ports:
      - 8000:8000
    depends_on:
      - zipkin-server
      - naming-server
      - exchange-db
    networks:
      - fernando-network

  book-service:
    image: fernandodelima/book-service:0.0.1-SNAPSHOT
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/book_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: fernando
    ports:
      - 8100:8100
    depends_on:
      - zipkin-server
      - naming-server
      - book-db
    networks:
      - fernando-network

networks:
  fernando-network:
    name: fernando-network
    driver: bridge